site_name: clj-fakes
site_description: Project documentation for clj-fakes framework.

repo_url: https://github.com/metametadata/clj-fakes/

theme: flatly

pages:
- Home: 'index.md'
- User Guide: 'user-guide.md'
- Developer Guide: 'dev-guide.md'
